name: Test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: set vars
        run: |
          NPM_TOKEN=testest
          echo NPM_TOKEN=$NPM_TOKEN >> $GITHUB_ENV

      - name: Get latest version tag
        id: latest-version
        run: |
          echo "::set-output name=version::$(curl -s $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/tags | jq '[ .[].name | select(test("^v")) ] | max_by(split("."))')"

      - name: Print latest version
        run: |
          echo ${{ steps.latest-version.outputs.version }}

      - name: Hello World
        run: |
          echo "Hello World!"

      - name: Install deps
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          cat .npmrc
          echo $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: JS
        run: |
          node -e "console.log('Hello JS!')"

      - name: Echo
        run: |
          echo "GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
