name: Test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Test
        run: |
          curl $GITHUB_API/repos/$GITHUB_REPOSITORY/tags
      - name: Get latest tag
        id: latesttag
        run: |
          echo "::set-output name=tag::$(curl -s $GITHUB_API/repos/$GITHUB_REPOSITORY/tags | jq '[ .[].name | select(test("^v")) ] | max_by(split("."))')"

      - name: Print latest tag
        run: |
          echo ${{ steps.latesttag.outputs.tag }}

      - name: Hello World
        run: |
          echo "Hello World!"

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: JS
        run: |
          node -e "console.log('Hello JS!')"

      - name: Echo
        run: |
          echo "GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
