name: Test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Hello World
        run: |
          echo "Hello World!"

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: JS
        run: |
          node -e "console.log('Hello JS!'')"

      - name: Echo
        run: |
          echo "GITHUB_ACTION_REPOSITORY: ${{ env.GITHUB_ACTION_REPOSITORY }}"
          echo "GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}"
